### ISSUE TITLE
Capability to determine if cloudProvider.testContext returns true account number after success.

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#15]
Clouds like "Joyent" does not seem to be returning a true account number after cloudProvider.testConext is invoked. A capability to determine clouds that cannot send back a true account number or a fix to joyent driver to return true account number after the context test would be very helpful.

**Comment by drewlyall** [comment]
So, in the case of Joyent (and some other clouds probably) we do little more than return the account number specified in the context object assuming we can successfully test the cloud connection.
I don't think a capability is quite right for this situation rather, we need to find a better value to return from the methods that suits the needs in this case.
Can you open an internal FB ticket for that one?
