### ISSUE TITLE
CloudUser Improvements

### ISSUE THREAD

**Issue by erik-johnson** [dasein-cloud/dasein-cloud-core#33]
As discussed with @maksimov this morning we would like these features added for managing cloud users.
1. Methods for making Access Keys Inactive/Active
2. New Capability: Access Key Per User Limit (2 in AWS)
3. Password Reset for Console Access
4. New Capabilities: IAM user password requirements (API requirements + account password policy)
5. Add Created Date and Password Last Used date to CloudUser (http://docs.aws.amazon.com/IAM/latest/APIReference/API_User.html)

Thanks!

**Comment by drewlyall** [comment]
Released in core-2015.10.1
