### ISSUE TITLE
Capability for sshkey requirement on windows launch for passwords

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#4]
Some clouds like AWS and Eucalytpus requires the user provide sshKey during windows server launches to encrypt and decrypt windows password. A cloud capability to determine this requirement based on OS platforms would be very useful.

**Comment by drewlyall** [comment]
VirtualMachineCapabilities has "identifyShellKeyRequirement(Platform platform)" - is this sufficient?

**Comment by binod33** [comment]
That method specifically does not tell us whether the root vm password was encrypted using the ssh key.
Maybe a capability that tells us that the root vm password for specific platform vm will be encrypted using ssh key might be useful?

**Comment by drewlyall** [comment]
Added in 2015.09
