### ISSUE TITLE
Listing products based on Image

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#41]
The new core is moving towards defaulting to listingProducts based on machine image Id.
But it looks like GCE does not require a machine image Id to list products. Do you think a requirement capability to know for what clouds machine image id is optional or required might be helpful? Knowing this before hand will let the user know if they have to fetch a machine image id from a specific region just to extract products supported in that region.

**Comment by maksimov** [comment]
Binod, technically there shouldn't be a case where one needs to look at products without the imageId ready at hand - unless for some narrow use-case where having a (possibly hardcoded, well-known) imageId is possible.

**Comment by drewlyall** [comment]
Indeed - to follow Stas' point, Dasein no longer considers a machineImageId as optional.
The underlying cloud might not need it but to simplify the API Dasein always does.
It should have little to no effect on the client and the driver will only make a cloud call if it is necessary.
