### ISSUE TITLE
Capability to determine the form of CIDR 

### ISSUE THREAD

**Issue by binod33** [dasein-cloud/dasein-cloud-core#5]
There are cases where some cloud expects a CIDR in the form w.x.y.z/n (10.0.0.0/24)
And some clouds like Azure in the form of lowIp::highIp (10.0.0.0::10.0.0.255). A cloud capability to figure out the this requirement would be really helpful.

**Comment by drewlyall** [comment]
Can you be more specific on this?
Where do you need to provide the lowIp::highIp for for Azure?
I thought it would be somewhere like createVlan but that takes a regular cidr notation.

**Comment by binod33** [comment]
https://github.com/dasein-cloud/dasein-cloud-azure/blob/2015.06/src/main/java/org/dasein/cloud/azure/platform/AzureSqlDatabaseSupport.java#L41-#L52
When adding rdbms rules acccess, it expects the cidr to be in a certain format.

**Comment by drewlyall** [comment]
We're going to take a look at changing this in the driver rather than adding a capability for it.
We can re-address it later on if we can't express what we need here with a traditional cidr.

**Comment by drewlyall** [comment]
So, we looked at the code and Dasein was originally using traditional cidr notation. Do you know why DCM needed the :: split version?

**Comment by drewlyall** [comment]
Okay, so the Azure needs a change but is there any reason why we can't just use a cidr to express that as we do elsewhere and allow Dasein to convert that to a range?

**Comment by drewlyall** [comment]
Okay - we're making some changes in the Azure driver to remove the need for this capability.
